---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aless.
--- DateTime: 22/06/2021 23:17
---
local function create_traits()
    local diabetic = TraitFactory.addTrait("diabetic", getText("UI_trait_diabetic"), -22, getText("UI_trait_diabeticdesc"), false, false);
    diabetic:addXPBoost(Perks.Lightfoot,5)
end

Events.OnGameBoot.Add(create_traits);
